const express = require("express")
const authJwt = require("../middlewares/JWT.middlewares")
const categoriesMiddlewares = require("../middlewares/validation/categories.middlewares")
const MiddlewarePermissions = require("../middlewares/permissions.middlewares")
const router = express.Router()

router.get("/",authJwt,MiddlewarePermissions,allCategories)
router.post("/",authJwt,MiddlewarePermissions,ajoutCategories)
router.patch("/:id",authJwt,MiddlewarePermissions,modifierCategories)
router.delete("/:id",authJwt,MiddlewarePermissions,suppressionCategories)